
FIND_PACKAGE(OpenGL REQUIRED)
list(APPEND RedBoxApp_libraries_list ${OPENGL_LIBRARY})
FIND_PACKAGE(OpenAL REQUIRED)
list(APPEND RedBoxApp_IncludeDir_list ${OPENAL_INCLUDE_DIR})
list(APPEND RedBoxApp_libraries_list ${OPENAL_LIBRARY})

#QT##########
set(QT_USE_QTOPENGL TRUE)   
set(QT 1)	
ADD_DEFINITIONS("-DQT")
FIND_PACKAGE( Qt4 REQUIRED)	
INCLUDE( ${QT_USE_FILE} )

list(APPEND RedBoxApp_IncludeDir_list ${QT_INCLUDE_DIR} ${QT_QTOPENGL_INCLUDE_DIR})
list(APPEND RedBoxApp_libraries_list ${QT_LIBRARIES} ${QT_QTOPENGL_LIBRARY})

INCLUDE_DIRECTORIES( ${CMAKE_BINARY_DIR} )
